version: '3.8'

services:
  php:
    build: ./php
    volumes:
      - ./php:/var/www/html
    depends_on:
      - mysql

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./php:/var/www/html
    depends_on:
      - php

  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'mydatabase'
      MYSQL_USER: 'myuser'
      MYSQL_PASSWORD: 'mypassword'
      MYSQL_ROOT_PASSWORD: 'rootpassword'
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
