---
- name: Deploy Dockerized PHP application with Nginx and MySQL
  hosts: officepc
  become: yes
  gather_facts: no

  vars:
    nginx_listen_port: 80
    nginx_server_name: localhost
    nginx_root: /var/www/html
    nginx_index: index.php index.html
    php_fastcgi_pass: php:9000

  tasks:
    - name: Install Docker and Docker Compose
      become: yes
      apt:
        name:
          - docker.io
          - docker-compose
        state: present

    - name: Create directories for Nginx and PHP
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - /opt/docker_app/nginx
        - /opt/docker_app/php

    - name: Generate NGINX configuration
      template:
        src: templates/nginx/nginx.conf.j2
        dest: /opt/docker_app/nginx/nginx.conf
        mode: '0755'
      notify: 
        - Restart Docker Service
        - Reload Container

    - name: Copy Docker Compose files
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      loop:
        - { src: "docker-compose.yaml", dest: "/opt/docker_app" }
        - { src: "php/Dockerfile", dest: "/opt/docker_app/php" }
        - { src: "php/index.php", dest: "/opt/docker_app/php" }

    - name: Build and run docker-compose
      command: docker-compose up -d
      args:
        chdir: /opt/docker_app

  handlers:
    - name: Restart Docker Service
      service:
        name: docker
        state: restarted

    - name: Reload Container
      command: docker-compose restart
      args:
        chdir: /opt/docker_app
